// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2_MMR08ChjX-xJ8WJkkiBFN1MSEaQdk',
    appId: '1:1064967460626:web:64a540d55fb0be8199c5cb',
    messagingSenderId: '1064967460626',
    projectId: 'fire-notifications-b065c',
    authDomain: 'fire-notifications-b065c.firebaseapp.com',
    storageBucket: 'fire-notifications-b065c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWUwSEzKtROe8wQP-binZe7KtPAO0IE8k',
    appId: '1:1064967460626:android:6df0d13fe6c3884b99c5cb',
    messagingSenderId: '1064967460626',
    projectId: 'fire-notifications-b065c',
    storageBucket: 'fire-notifications-b065c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVI4QFRgD5wsRWWiKPbieO129dY4kx0g',
    appId: '1:1064967460626:ios:538bd4bd32f41c1e99c5cb',
    messagingSenderId: '1064967460626',
    projectId: 'fire-notifications-b065c',
    storageBucket: 'fire-notifications-b065c.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVI4QFRgD5wsRWWiKPbieO129dY4kx0g',
    appId: '1:1064967460626:ios:39274ebf7b1f537499c5cb',
    messagingSenderId: '1064967460626',
    projectId: 'fire-notifications-b065c',
    storageBucket: 'fire-notifications-b065c.appspot.com',
    iosBundleId: 'com.example.notificationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2_MMR08ChjX-xJ8WJkkiBFN1MSEaQdk',
    appId: '1:1064967460626:web:a2fb67b09afec10899c5cb',
    messagingSenderId: '1064967460626',
    projectId: 'fire-notifications-b065c',
    authDomain: 'fire-notifications-b065c.firebaseapp.com',
    storageBucket: 'fire-notifications-b065c.appspot.com',
  );
}